# Generated by Django 4.0.4 on 2022-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidder',
            field=models.CharField(max_length=30),
        ),
    ]
