# Generated by Django 4.0.4 on 2022-07-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.autionlisting'),
        ),
    ]
