# Generated by Django 4.0.6 on 2022-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autionlisting',
            old_name='bid',
            new_name='close_bid',
        ),
        migrations.AddField(
            model_name='autionlisting',
            name='bidder',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='bids',
        ),
    ]
