# Generated by Django 4.0.6 on 2022-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_autionlisting_close_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autionlisting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
