# Generated by Django 4.0.6 on 2022-10-31 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_autionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autionlisting',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
